// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0u7gDphca-7TMz2PoJfFZglqvdUBGvpo',
    appId: '1:540557952860:web:1655d14c6e2b06b2e66399',
    messagingSenderId: '540557952860',
    projectId: 'supply-list-database',
    authDomain: 'supply-list-database.firebaseapp.com',
    databaseURL: 'https://supply-list-database-default-rtdb.firebaseio.com',
    storageBucket: 'supply-list-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBailavCDm22746RpGJdtojrk_OmunameE',
    appId: '1:540557952860:android:7ea75da065f40746e66399',
    messagingSenderId: '540557952860',
    projectId: 'supply-list-database',
    databaseURL: 'https://supply-list-database-default-rtdb.firebaseio.com',
    storageBucket: 'supply-list-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyVUowhlDN_XUQ3o05wP82y-rCjFHmqg',
    appId: '1:540557952860:ios:cd06c28cc3991ddee66399',
    messagingSenderId: '540557952860',
    projectId: 'supply-list-database',
    databaseURL: 'https://supply-list-database-default-rtdb.firebaseio.com',
    storageBucket: 'supply-list-database.appspot.com',
    iosClientId: '540557952860-0hdqbf7kqvfuetiibgg7vofoikgvj5pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPrepperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtyVUowhlDN_XUQ3o05wP82y-rCjFHmqg',
    appId: '1:540557952860:ios:cd06c28cc3991ddee66399',
    messagingSenderId: '540557952860',
    projectId: 'supply-list-database',
    databaseURL: 'https://supply-list-database-default-rtdb.firebaseio.com',
    storageBucket: 'supply-list-database.appspot.com',
    iosClientId: '540557952860-0hdqbf7kqvfuetiibgg7vofoikgvj5pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPrepperApp',
  );
}
